apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: debasnan-role2
  namespace: debu-project
rules:
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch