apiVersion: v1
kind: Service
metadata:
  labels:
    app: debu-db
  name: debubd-lb
  namespace: 
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: debu-db
  type: ClusterIP
status:
  loadBalancer: {}
