apiVersion: v1
kind: Service
metadata:
  labels:
    app: debu-webapp
  name: debudb-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: debu-webapp
  type: LoadBalancer
status:
  loadBalancer: {}
