apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: debu-webapp
  name: debu-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debu-webapp
  strategy: {}
  template:
    metadata:
      labels:
        app: debu-webapp
    spec:
      containers:
      - image: adminer
        name: adminer
        ports:
        - containerPort: 8080
        resources: {}
status: {}
